#!/bin/bash

cachepath="/var/cache/m0nitor/"

# Argument parsing code copied from:
# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f

if [[ "$#" -eq 0 ]]; then
    echo "m0nitor: a script for alerting via discord if a host goes online or offfline."
    echo "Arguments are required unless otherwise specified"
    echo ""
    echo "-d/--debug (opt.)         Prints debug messages during run"
    echo "--max-ping-fails (opt.)   Number of times ping can fail before an alert is sent"
    echo "--host                    IP address or fully qualified domain name of host"
    echo "--server-name             Name of server in alert"
    echo "--webhook                 Discord webhook URL"
    exit 0
fi

PARAMS=""

while (( "$#" )); do
    case "$1" in
        -d|--debug)
            debug_echo="echo"
            shift
            ;;
        --host)
            if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
                host=$2
                shift 2
            else
                echo "Error: Argument for $1 is missing" >&2
                exit 1
            fi
            ;;
        --max-ping-fails)
            if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
                max_fails=$2
                shift 2
            else
                echo "Error: Argument for $1 is missing" >&2
                exit 1
            fi
            ;;
        --server-name)
            if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
                server_name=$2
                shift 2
            else
                echo "Error: Argument for $1 is missing" >&2
                exit 1
            fi
            ;;
        --webhook)
            if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
                webhook=$2
                shift 2
            else
                echo "Error: Argument for $1 is missing" >&2
                exit 1
            fi
            ;;
        -*|--*=) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) # preserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done

# Set positional arguments in their proper place
eval set -- "$PARAMS"


# Handle missing parameters
if [[ -z ${host+x} ]]; then
    echo "--host not specified. Please specify host with either IP address or fully qualified domain name."
    exit 1
fi

if [[ -z ${server_name+x} ]]; then
    echo "--server-name not specified. Please provide a name for this server to be included in alert messages."
    exit 1
fi

if [[ -z ${webhook+x} ]]; then
    echo "--webhook not specified. Please provide a webhook URL to send alerts to."
    exit 1
fi

if [[ -z ${debug_echo+x} ]]; then
    debug_echo=":"
fi

$debug_echo $(date --iso-8601="seconds")

if [[ -z ${max_fails+x} ]]; then
    echo "--ping-max-fails not specified. Setting max_fails=1"
    max_fails=1
fi


statefile="$cachepath$host"

# Use negative form of booleans so 0 is good and 1 is bad to match unix command exit codes
if [ -f "$statefile" ]; then
    read -r fail_count <"$statefile"
    $debug_echo "Read value fail_count=$fail_count from statefile in $statefile"

    num_regex='^[0-9]+$'
    if ! [[ $fail_count =~ $num_regex ]]; then
        $debug_echo "Invalid state fail_count=$fail_count. Setting fail_count=1 to assume server is offline"
        fail_count=1
    else
        $debug_echo "State is valid"
    fi
else
    $debug_echo "Could not find statefile in $statefile. Setting fail_count=-1 to mark first run."
    fail_count=-1
fi

ping_failure=$( ping -c 1 $host 2>&1 >/dev/null )$?

if [[ $ping_failure = 0 ]]; then
    $debug_echo "Succesfully pinged $server"
    if [[ $fail_count -eq -1 ]]; then
        msg="m0nitor first run: $server_name is online."
        $debug_echo "Sending webhook message: \"$msg\""
        curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$msg\"}" $webhook
        printf 0 > "$statefile"

    elif [[ $fail_count -ge $max_fails ]]; then
        msg="$server_name is back online"
        $debug_echo " Sending webhook message: \"$msg\""
        curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$msg\"}" $webhook
        printf 0 > "$statefile"
    fi

else
    $debug_echo "Failed to ping $server"

    if [[ $fail_count -eq -1 ]]; then
        msg="m0nitor first run: $server_name is offline."
        $debug_echo "Sending webhook message: \"$msg\""
        curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$msg\"}" $webhook
        printf 1 > "$statefile"
        exit 0

    elif [[ $fail_count -eq $max_fails ]]; then
        msg="$server_name has been offline for $max_fails pings"
        $debug_echo "Sending webhook message: \"$msg\""
        curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$msg\"}" $webhook
    fi
    printf $(($fail_count + 1)) > "$statefile"
fi